trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- script: |
    git config user.email "ron.buckton@microsoft.com"
    git config user.name "Ron Buckton"
  displayName: 'configure git user'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    gulp build
  env:
    DOCS_DIR: $(Build.ArtifactStagingDirectory)
  displayName: 'gulp build'

- script: |
    git fetch origin gh-pages
    git checkout gh-pages --force
    git clean -fdx
  displayName: 'checkout gh-pages'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.ArtifactStagingDirectory)
    TargetFolder: $(Build.SourcesDirectory)
    OverWrite: true
  displayName: 'Copy built outputs'

- script: |
    git add --all
    git commit -m "(chore) Publish update to gh-pages"
    git status
    git push origin gh-pages;
  displayName: 'publish gh-pages'