# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    gulp build
  env:
    DOCS_DIR: $(Build.ArtifactStagingDirectory)
  displayName: 'gulp build'

- script: |
    git rm -rf .
    git clean -fdx
    git checkout gh-pages
    touch .nojekyll
    cp -a $(Build.ArtifactStagingDirectory)/. .
    git config user.email "ron.buckton@microsoft.com"
    git config user.name "Ron Buckton"
    git add --all
    git commit -m "(chore) Publish update to gh-pages"
    git push origin gh-pages;
  displayName: 'publish gh-pages'