trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true

- script: |
    git config user.email "ron.buckton@microsoft.com"
    git config user.name "Ron Buckton"
  displayName: 'configure git user'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    gulp build
  displayName: 'gulp build'

- task: CopyFiles@2
  inputs:
    SourceFolder: docs
    TargetFolder: $(Build.ArtifactStagingDirectory)
    OverWrite: true
  displayName: 'Copy Build Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

- script: |
    git fetch origin gh-pages
    git checkout gh-pages --force
    git clean -fdx
  displayName: 'checkout gh-pages'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.ArtifactStagingDirectory)
    TargetFolder: $(Build.SourcesDirectory)
    OverWrite: true
  displayName: 'Copy built outputs'

- script: |
    git add --all
    git status
    git commit -m "(chore) Publish update to gh-pages"
    git push origin gh-pages
  displayName: 'publish gh-pages'